"""empty message

Revision ID: cfff7708d817
Revises: 
Create Date: 2020-09-19 15:11:43.855398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfff7708d817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("polls") as batch_op:
        op.add_column('topics', sa.Column('status', sa.Boolean(), default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'status')
    # ### end Alembic commands ###
